version: "3"

services:
  app-phx:
    image: elixir:1.14.3-alpine
    container_name: app-phx
    command: >
      sh -c "apk --no-cache add postgresql-client inotify-tools
      && mix local.hex --force
      && mix local.rebar --force
      && mix archive.install hex phx_new 1.7.0-rc.2 --force
      && echo y | mix phx.new . --no-ecto
      && mix setup
      && mix phx.server"
    environment:
      APP_HOME: /app
    working_dir: /app
    volumes:
      - ./src:/app
      - ./config/dev.exs:/app/config/dev.exs
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    container_name: db-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
