version: "3"

services:
  app-phx:
    image: phregi.azurecr.io/app-phx:latest
    container_name: app-phx
    command: >
      bash -c "apt-get update
      && apt-get install -y postgresql-client inotify-tools
      && mix local.hex --force
      && mix local.rebar --force
      && mix archive.install hex phx_new 1.7.0-rc.2 --force
      && echo y | mix phx.new . --no-ecto
      && mix setup
      && mix phx.server"
    environment:
      APP_HOME: /app
    working_dir: /app
    volumes:
      - ${WEBAPP_STORAGE_HOME}/src:/app
      - ${WEBAPP_STORAGE_HOME}/config/dev.exs:/app/config/dev.exs
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
  db-pg:
    image: phregi.azurecr.io/db-pg:latest
    container_name: db-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/pgdata:/var/lib/postgresql/data
